name: task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  sqflite: ^2.2.8+2
  path: ^1.8.2
  uuid: ^3.0.7
  dotted_border: ^2.0.0+3
  intl: ^0.18.1
  flutter_week_view: ^1.3.0
  flutter_svg: ^1.1.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
